server:
  port: 8761

spring:
  application:
    name: discovery-service

eureka:
  instance:
    hostname: ${eureka.instance.hostname}
  client:
    register-with-eureka: false
    fetch-registry: false